### ISSUE TITLE
ama-logs prometheus sidecar purpose when Managed Prometheus integration is enabled

### ISSUE THREAD

**Issue by kamilzzz** [Microsoft/Docker-Provider#1236]
What's the purpose of prometheus sidecar in `ama-logs` DaemonSet when Managed Prometheus integration is enabled on the cluster?

I was investigating memory requests on our nonprod cluster using burstable nodes with 4GB RAM and noticed `ama-logs` is pod with the highest memory request compared to all other addons. Looks like logs container requests 325 MB of memory and prometheus sidecar requests additional 225 MB of memory.

I started wondering what's the purpose of prometheus sidecar in setup where Managed Prometheus integration is also enabled and `ama-metrics` pods are deployed into the cluster. My understanding is that in such scenario by default all Prometheus metrics are scraped by `ama-metrics` pods and not by `ama-logs` pods. I guess scraping Prometheus metrics with `ama-logs` was a previous way of doing things where it stored Prometheus metrics in Log Analytics tables. If so, wouldn't it be a good idea to allow users of Container Insights to be able to opt-out from deploying prometheus sidecar as part of `ama-logs`? We could save some memory available for other services that way.

Also, on smaller nodes 600 MB of memory requested for `ama-logs` seems quite high considering this pod is deployed on all nodes. It reserves about 20% of available memory on 4GB RAM nodes running AKS >1.29. For <1.29 it would be even more in terms of relative values as 1.29 reduced some kube-reserved memory so we can get more memory available.

**Comment by vdiec** [comment]
@kamilzzz Our recommendation is to use [Azure Monitor managed service for Prometheus](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/prometheus-metrics-overview#enable) to collect Prometheus metrics which are stored in an Azure monitor workspace. 
As you mentioned, scraping Prometheus metrics with ama-logs stores Prometheus metrics in Log Analytics.  
We continue to offer both methods since some customers prefer using Log Analytics. If you plan to enable Managed Prometheus, you can [disable metric collection through ama-logs from the sidecar](https://github.com/microsoft/Docker-Provider/blob/ci_prod/kubernetes/container-azm-ms-agentconfig.yaml#L99).

The high resource is a known issue, and we plan on addressing this in June. We will update this thread if anything changes! Thank you

**Comment by kamilzzz** [comment]
@vdiec Thanks for info.
