### ISSUE TITLE
ama-logs pod in constant crash loop, eventually resulting in CrashLoopBackOff

### ISSUE THREAD

**Issue by wsdnv** [Microsoft/Docker-Provider#1305]
We've faced ongoing problem with `ama-logs` pods crashing in a loop, eventually resulting in `CrashLoopBackOff`.
It fails every 5-10min with following error message in `ama-logs` container logs
```
2024-08-12 12:49:19.347	"config::error::Exception while parsing dcr : No JSON file found in the specified directory. Check if mdsd is running in MSI mode. DCR Json data: "
2024-08-12 12:54:19.846	"config::error::Exception while parsing dcr : No JSON file found in the specified directory. Check if mdsd is running in MSI mode. DCR Json data: "
2024-08-12 12:59:19.447	"config::error::Exception while parsing dcr : No JSON file found in the specified directory. Check if mdsd is running in MSI mode. DCR Json data: "
```
and following reason in `kubectl describe`
```
  ama-logs:
[..]
    Image:         mcr.microsoft.com/azuremonitor/containerinsights/ciprod:3.1.22
[..]
    Last State:    Terminated
      Reason:      Error
      Message:     dcr_env_var has been updated - dcr config changed

      Exit Code:    143
[..]
    Restart Count:  45
```

I guess that this mechanism was introduced to restart container one time in order to reload config, but this is done every 5 minutes on some nodes.

### Possible reason

Investigated this a bit and from my understanding this is what happens:
1. `ama-logs` pod is spawned
2. At the beginning `/opt/dcr_env_var` file is created and it's empty
    ```
    # cat /opt/dcr_env_var
    # ls -lh /opt/dcr_env_var
    -rw-r--r--    1 root     root           0 Aug 12 11:53 dcr_env_var
    ```
3. Every 60s liveness probe reloads script generating `/opt/dcr_env_var` and checks if file has been modified
    https://github.com/microsoft/Docker-Provider/blob/4fd872d415b6799cb7914e9e3663ca58eb5d10da/build/linux/installer/scripts/livenessprobe.sh#L25
4. After few minutes (mostly 5min) file `/opt/dcr_env_var` suddenly has variable set
    ```
    # cat /opt/dcr_env_var
    LOGS_AND_EVENTS_ONLY=false
    # ls -lh /opt/dcr_env_var
    -rw-r--r--    1 root     root          27 Aug 12 11:56 dcr_env_var
    ```
5. Liveness probe sees that file has been modified and fails with error exit code, probably with an intent to restart the pod once
    ```
        Last State:    Terminated
          Reason:      Error
          Message:     dcr_env_var has been updated - dcr config changed
    
          Exit Code:    143
    ```
    https://github.com/microsoft/Docker-Provider/blob/4fd872d415b6799cb7914e9e3663ca58eb5d10da/build/linux/installer/scripts/livenessprobe.sh#L28
6. After the restart situation happens again and again, in the loop

**Comment by ganga1980** [comment]
@wsdnv  - If you are seeing the ama-logs pods getting continuously restarted, which means likely either ContainerInsights Extension DCR not created as part of the onboarding or ama-logs agent pod failed to download and failure can happen either agent cant reach the endpoint because the endpoint or port blocked at the firewall or network policy.

1.  Can you please check if the ContainerInsights Extension DCR association exists on the AKS cluster -

 az monitor data-collection rule association list --resource "/subscriptions/subId/resourcegroups/rgName/Microsoft.ContainerService/managedClusters/clusterName" ?

Note> please replace the subId, rgName and clusterName with actual values.

2. can you please share the logs of ama-logs pods - 
kubectl logs <ama-logs-pod-name> -n kube-system -c ama-logs

**Comment by wsdnv** [comment]
Found the reason, it was networking issue - probably firewall and/or private link misconfiguration on our side. Here are some details for the others that also face such problem.

In our case some of Azure serivces FQDNs are not resolving, what is the root cause of the problem.
1. `ama-logs` try to connect to `global.handler.control.monitor.azure.com`, probably trying to get variable value
2. This fails few times, as domain name is not resolved (domain not known)
3. After few tries `ama-logs` eventually fallbacks to some other endpoints
    ```
    # /var/opt/microsoft/linuxmonagent/log/mdsd.err
    [/__w/1/s/external/WindowsAgent/src/shared/mcsmanager/lib/src/RefreshConfigurations.cpp:318,GetAgentConfigurations]Could not obtain configuration from https://global.handler.control.monitor.azure.com after first round of tries. Will try again with a fallback endpoint. ErrorCode:1310977
    ````
4. Fallback endoint works, allowing to pull variable value
5. `ama-logs` container restarts, assuming that variable value has been updated

**Comment by wsdnv** [comment]
Root cause is problem with DNS on our side, but I think it's worth modifying the code to fallback to other endpoints instantly. Retrying 4 times before fallback doesn't make it more stable in this case, pod is failing eventually anyway.

**Comment by ganga1980** [comment]
Thanks for the update. If the global endpoint global.handler.control.monitor.azure.com not resolved then it will fall back to regional endpoint. Looks like  because networking issue either of the endpoint couldn't resolve.  We will see if there is any thing we would need to improve in our side. Considering this is networking issue which has been resolved and closing this issue.
