### ISSUE TITLE
[Feature request] Configure reporting interval

### ISSUE THREAD

**Issue by MartinKosicky** [microsoft/Docker-Provider#534]
Hello the monitoring of metrics per container is so expensive for us that we would either not use it all, or preferebly tune down the monitoring ammount. We dont really need metrics every minute,  if we do this every 2 minutes we would be OK. So what would be nice if there was a way how to configure the interval to log container metrics

**Comment by saaror** [comment]
Thanks Martin for reaching out! We use these container metrics to light-up our out-of-the-box container insights experience which you see in portal. That's why we don't allow customers to alter the frequency. That being said in future we plan to bring metrics in metrics store which would reduce your Log analytics cost. 

We are also running private preview for cheaper SKU of Log analytics to reduce cost of your "container logs." Let me know if you would want to try that out, that can reduce your container-log cost considerably thereby reducing overall-monitoring cost.

**Comment by MartinKosicky** [comment]
Im sorry but if you allow alter the frequency i dont see how would that
interfer with the ability to light-up out of the box frequency. Also you
have ability to configure all kinds of filters in oms agent already (aks
you can filter on namespaces for example), so this would be just another
configuration

**Comment by saaror** [comment]
Hey Martin, the filters we have apply only for *stdout/stderror container logs*; which are used nowhere in our portal experience. If you see our portal experience we have filters, logic to calculate 90th percentile etc all of that would be broken if we allow customer to config the metrics.

I hear your ask and we will have something in future by updating our metrics platform.

**Comment by MartinKosicky** [comment]
But i thought the 90th percentile is calculated by standard log analytics
logic (since log analytics doesnt care what it calculate s 90th percentile
of and who sent the data and how often) of the Perf table.  Anyway since we
are paying over 120k yearly on log analytics and it most likely would go up
due to our increasing number of services and customer, it seems to be
getting cheaper to integrate some custom monitoring on our pods and nodes
and pay the money for someone elses service. Or just fork your oms agent
and tune it down ourselves.
