### ISSUE TITLE
Critical vulnerability (CVE-2017-10906)

### ISSUE THREAD

**Issue by FatGuru** [microsoft/Docker-Provider#536]
Hi, I am part of an InfoSec team and we detected the following critical vulnerability in image: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod02232021 

Please validate. Thanks in advance!

**Critical vulnerability (CVE-2017-10906)**

Description:                      Escape sequence injection vulnerability in Fluentd versions 0.12.29 through 0.12.40 may allow an attacker to change the terminal UI or execute arbitrary commands on the device via unspecified vectors.
Installed Resource:         fluentd 0.12.40
Fixed Version:                  0.12.41
Published by NVD:          2017-12-08
CVSS Score:                      NVD CVSSv2    10.0
Remediation:                   Upgrade package fluentd to version 0.12.41 or above.
Full Path:            /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.4.0/specifications/fluentd-0.12.40.gemspec

**Comment by daweim0** [comment]
Hi, thank you for bringing this to our attention. We do use fluentd 0.12.40. We likely won't update until our next release though

**Comment by vishiy** [comment]
@FatGuru  - Whats the scanning tool you used ?

**Comment by FatGuru** [comment]
Thank you very much @daweim0 for your quick response. 
Could you provide an ETA for the next release?

**Comment by daweim0** [comment]
Hi @FatGuru, sorry for the late reply. We are not using the vulnerable plugin ([parser](https://github.com/microsoft/OMS-Agent-for-Linux/pull/1136/files/4862468d242dc0ba67f14ea2ba172cceb95bb599#diff-ad547aa0806c90e709a3f65364c79d737bd09ff165fabc62770b635bf7edea83)), so it should not be triggerable in our container (can't give a concrete answer since the procedure for triggering the vulnerability is not disclosed). 
However, a newer agent without the vulnerability won't be rolled out and widely available for another month (@vishiy correct me if I'm wrong). We get fluentd from omsagent, and we don't have time to integrate the newest version of omsagent before the next release. Does that help at all?

**Comment by FatGuru** [comment]
Hi @daweim0, thank you very much for taking the time to answer. I will copy your inputs to our team. 
Is always good that you've acknowledge it and that you are planning to remediate.
I guess you can keep this thread open until the fix happens. Thanks again!

**Comment by daweim0** [comment]
Hi @FatGuru, a quick update. Through an unfortunate turn of events, our release schedule was pushed back by a little over a month. Our current adjusted schedule shows us upgrading to Fluentd 1.12.2 in the next few weeks. That should be available in all regions by the first or second week of July.

**Comment by FatGuru** [comment]
Hi @daweim0, great! Thanks for keeping us posted :)

**Comment by lestaat** [comment]
Hi @daweim0 do you know what version/patch of AKS will be rolling out along w/the fix?

**Comment by daweim0** [comment]
Hi @lestaat, It should start rolling out next Thursday (6/17). It will then take two or three weeks to reach all regions.

**Comment by joby-thomas** [comment]
Fix has been rolled with 06112021 version
