### ISSUE TITLE
OMS Agent does not respect namespace exclusion of custom configmap container-azm-ms-agentconfig

### ISSUE THREAD

**Issue by Ziphone** [microsoft/Docker-Provider#737]
Version: mcr.microsoft.com/azuremonitor/containerinsights/ciprod:ciprod01312022
Platform: AKS

I'm using the proposed configuration template [1], and it seems to get loaded (according to the logs). The omsagents still seem not to respect the arrays of excluded namespaces. If I disable exportation of stdout and stderr, it takes effect, but filtering (while collection is enabled) does not work.

1 - https://github.com/microsoft/Docker-Provider/blob/ci_dev/kubernetes/container-azm-ms-agentconfig.yaml

**Comment by VincentVerweij** [comment]
@Ziphone you did close this issue some time ago, but what was the solution? I did create a configmap with name `container-azm-ms-agentconfig` where I did exclude some namespaces:
```
[log_collection_settings]
   [log_collection_settings.stdout]
      enabled = true
      exclude_namespaces = ["kube-system", "my-namespace"]

   [log_collection_settings.stderr]
      enabled = true
      exclude_namespaces = ["kube-system", "my-namespace"]
```

It is deployed in my AKS cluster but still I am seeing some entries in the analytics workspace that come from namespace `kube-system`.
So not sure what went wrong, but it is seems you had the same issue.
Since you closed this yourself, I assume you had found a solution, or maybe some misconfiguration that you did figure out yourself causing you to close this.
